### PR TITLE
docs: Update README.mdx

### PR DESCRIPTION
**Pull request by Sarah-Roediger**
# Purpose of PR

Added clarification for button alignment to the section 'How to use Buttons'. These clarifications have been agreed upon with the design guild.

### CODE REVIEW

**Review by gui-santos — APPROVED** [review]
💙 

Thank you! 🙌

**Review by burakukula — APPROVED** [review]
👏. Thx a lot!!!
In order to fix the commit-check, changing the title of the PR to "docs:  Update README.mdx" should do the trick.

**Comment by nikazawila** [comment]
great job there @Sarah-Roediger 💕

**Review by nikazawila — APPROVED** [review]

**Comment by Sarah-Roediger** [comment]
Ooopsie, changed the title now! Thank you @burakukula and @nikazawila

**Comment by burakukula** [comment]
@Sarah-Roediger, sorry for the trouble. I think something totally not related to your PR is failing here. We have some prettier issues. You might need to run `yarn run prettier` from the command line in the main folder or I can do it for you, no problem.

**Comment by nikazawila** [comment]
@all-contributors add @Sarah-Roediger for doc

**Pull request merged**
