### PR TITLE
fix(issue 894): add labelText prop support to TextInput component

### PR DESCRIPTION
**Pull request by anilkk**
# Purpose of PR
To fix the issue #894 

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [ ] Tests are passing
- [x] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by anilkk** [comment]
This PR is my first contribution to **forma-36**. 
I have tested locally on my branch(ak-bug-fix-Aira-Label-TextInput-component) and also  **master** branch, both branches tests failed.
Screenshot 2021-05-18 at 23 12 23
Let me if I miss any step or if you have any feedback to me.  thanks.

**Comment by mshaaban0** [comment]
Hi @anilkk thanks, much appreciate the contribution. 
I think you need to build the `@contentful/forma-36-react-components` package with `yarn build` before running `yarn test`

Let me know if that helps

**Comment by anilkk** [comment]
Thanks @mshaaban0, I have updated the snapshots; all tests pass locally, but on **Circleci**, I still get the following error for both **anilkk:ak-bug-fix-Aira-Label-TextInput-component** and **master** branch. Let me know if I miss anything. Thanks
image

**Comment by mshaaban0** [comment]
Hi @anilkk for some reason your forked version run on your private circleci account, I have cherry-picked your commits to another PR #979 with an internal branch. 

Thanks a bunch for the contribution, and sorry for the trouble, we will look further into our circleci setup.

**Comment by mshaaban0** [comment]
@all-contributors add @anilkk for code,a11y

**Comment by mshaaban0** [comment]
@all-contributors add @anilkk for code

**Pull request closed without merging**
