### PR TITLE
fix(Badge): disable newlines

### PR DESCRIPTION
**Pull request by Chaoste**
# Purpose of PR

We have an example where there is not much space for the badge. Still, the text in the badge should never break the word for a new line.

image

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Review by ronaldronson — APPROVED** [review]

**Comment by denkristoffer** [comment]
In that case it might be good to also hide the overflow with an ellipsis? @domarku what do you think?

**Comment by Chaoste** [comment]
In our case, it was good to have it like it is now, so the text next to the badge would be shortened with an ellipsis.

**Comment by denkristoffer** [comment]
Sounds like it's about `flex-grow` and `flex-shrink` then, is that wrong?

**Comment by Chaoste** [comment]
You're probably right about the flex configuration, I will test it after the changes for Badge are live.

I adjusted the styles to show an ellipsis and added an example to the story:
Screenshot 2022-02-15 at 09 47 22

**Review by denkristoffer — APPROVED** [review]

**Pull request merged**
