### PR TITLE
fix: components using border radius tokens

### PR DESCRIPTION
**Pull request by burakukula**
Hello Forma36!

# Purpose of PR

In this PR I am updating border radiuses in react component. This the follow up to this proposal https://github.com/contentful/forma-36/issues/556

Couple of components will get new border radius becouse of that:

- Button - increasing to 4px
- Card -increasing to 4px
- EditorToolbar - increasing to 4px
- EditorToolbarButton - increasing to 4px
- Modal - increasing to 4px
- ModalHeader - increasing to 4px

Rest of the stuff is the replacement to use tokens.

**Question**: @domarku would you like to change the tooltip from 4px to 2px? I could do it in this PR.

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by burakukula** [comment]
Or maybe it should be a minor version ? 🤔

**Review by Gracegross — APPROVED** [review]
hell yeah!! ship ship

**Comment by gui-santos** [comment]
@burakukula I don't know if it worked. It looks like the old border-radius to me

Screenshot 2020-10-05 at 10 07 10

Screenshot 2020-10-05 at 10 07 05

**Comment by burakukula** [comment]
@gui-santos thank you for this catch. 🙇‍♀️ It should be fine now.

**Review by gui-santos — APPROVED** [review]

**Pull request merged**
