### PR TITLE
fix: 🐛 Fallback font collection of the sans

### PR DESCRIPTION
**Pull request by azer**
# Purpose of PR

Typography components look not nice as the primary sans font does not load in extensions.

This PR replaces "Helvetica" with a collection of sans fonts that look close to "'Avenir Next W01'".

Here is how SectionHeading looks like in my extension: 

It looks bigger, thicker, and uglier. Note that I use Linux which doesn't have Helvetica, so I get default system `sans-serif` font which leaves a bitter taste in your mouth.  

This is what we expect to see (when the font loads):

After adding the change in this PR, it looks as below: 

It's not identical, but close enough.

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by wichniowski** [comment]
cool so many fallbacks :) but maybe we should decide on one of the open source fonts and distribute it with the component library so we can be sure it will look a certain way if Avenir is not available. For that i'd also throw Lato in the mix :D

**Comment by azer** [comment]
@wichniowski I think this list was specifically crafted for selecting the best possible sans font in the default configurations of common operating systems, so they're good as fallback fonts. I know that changing the primary font is huge work, so just wanted to extend the fallback collection in this PR.

**Comment by m10l** [comment]
@azer Nice - seems like a good interim solution. Thanks for the PR 🎉

**Comment by domarku** [comment]
@wichniowski Choosing an open source font to distribute with the library is a separate effort we were considering. This is more of a reasonable interim solution, as @m10l said :)

**Pull request merged**
