### PR TITLE
feat: Add isSelected prop to entity list item

### PR DESCRIPTION
**Pull request by mgueyraud**
# Purpose of PR

Add a prop isSelected to the entity list item, and the corresponding styles of it. Basically the same way as [the card works](https://forma-36-react-components.netlify.app/?path=/story/components-card--default)

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/main/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by burakukula** [comment]
@mgueyraud Thanks so much for the contribution! Amazing! Codewise it looks great! 🙌
There are a couple of styling issues that we would have to figure out. Check it out:

Screenshot 2022-06-21 at 15 54 30
Screenshot 2022-06-21 at 15 54 56
Screenshot 2022-06-21 at 15 56 08

I will reach out to our design team for suggestions and come back to you with a visual proposal so we could adjust styles a bit. What do you think?

**Comment by burakukula** [comment]
Hey @mgueyraud!
Sure thing. In general, we need to make sure that there are no double borders visible when the element is selected (grey and blue visible at the same time). The pseudo element approach might be a quick win over here. I'm wondering how to solve the issue of double blue border, when 2 items are selected... 🤔 
But for now, let me just clarify details with the design team and come back to you, before we move forward, so you have all the info needed to work on that. Hope that's ok with you 🙂

**Comment by mgueyraud** [comment]
Hey @burakukula ,

Sounds good to me!

Will be working in that and let you know

**Comment by burakukula** [comment]
Hey @mgueyraud! how are you doing? 🙂
I wanted to check with you how is it going with changes for this PR. Did you face any issues? Can we help somehow?

**Comment by denkristoffer** [comment]
Thank you for the contribution! I'm going to close this PR for now as work has stalled. Feel free to ping us If you want to pick this back up in the future 🙂 And again, thank you for the contribution regardless.

**Pull request closed without merging**
