### PR TITLE
feat: puzzle icon

### PR DESCRIPTION
**Pull request by Spring3**
# Purpose of PR

Adding a puzzle icon to be used for marking extensibility items on the web page

Screenshot 2021-07-21 at 20 21 38

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by denkristoffer** [comment]
@Spring3 This doesn't quite look like the puzzle icon from Material to me, is it? 🤔

**Comment by Spring3** [comment]
@denkristoffer I used this https://materialdesignicons.com/icon/puzzle-outline

**Comment by denkristoffer** [comment]
I guess that's a community extension pack, we're using the icons from https://fonts.google.com/icons

**Comment by Spring3** [comment]
Oh, ok, I missed that change. I will update the icon then

**Comment by denkristoffer** [comment]
The CI build is blocked by https://github.com/contentful/forma-36/pull/1108 right now, sorry.

**Review by denkristoffer — APPROVED** [review]

**Pull request merged**
