### PR TITLE
feat: next code blocks

### PR DESCRIPTION
**Pull request by bgutsol**
# Purpose of PR

Move docs examples to separate files.

### CODE REVIEW

**Review by suevalov — COMMENTED** [review]
It looks as for me. Should we wait till the end of the week when we remove Gatsby website and point `https://v4.f36.contentful.com/` to Vercel?

When it's done, we can start moving examples component by component.

**Comment by bgutsol** [comment]
I'd say that the PR is not blocked by pages migration. Since I did it in a way that doesn’t break the build process for other not migrated pages.

**Comment by suevalov** [comment]
@bgutsol yeah, but if we merge it now, all examples in Menu will not be visible in `v4.f36.contentful.com`, right?

**Comment by bgutsol** [comment]
> @bgutsol yeah, but if we merge it now, all examples in Menu will not be visible in `v4.f36.contentful.com`, right?

ah, yes, you are right! But as a temporary solution, we can keep both, like:
image
So for nextJs it will get example from a file, but for Gatsby from codeblock. @suevalov  WDYT?

**Comment by suevalov** [comment]
@bgutsol works for me, but we need to tell the rest of the team

**Review by suevalov — APPROVED** [review]

**Pull request merged**
