### PR TITLE
fix(website): override style so what you select is what you edit

### PR DESCRIPTION
**Pull request by massao**
**Before**
image

**After**
image

### CODE REVIEW

**Review by gui-santos — APPROVED** [review]
UHmmm is this conflicting with @burakukula fix?

**Comment by gui-santos** [comment]
Anyway, we should go for the solution with less code hahahaha

**Comment by massao** [comment]
> UHmmm is this conflicting with @burakukula fix?

Different approach, #1876 adds padding to the wrapper, and the textarea is smaller, with this approach it makes so the textarea and pre tags use the entire space of the wrapper.
Up to @domarku to decide, since the main difference would be visual

**Comment by burakukula** [comment]
@massao let's go with this solution, it looks better that my hack.

**Pull request merged**
