### PR TITLE
feat(skeleton): compound component

### PR DESCRIPTION
**Pull request by denkristoffer**
Make a `Skeleton` compound component. Docs could be improved a bit to show off the pattern more.

### CODE REVIEW

**Review by burakukula — APPROVED** [review]
Nice!

**Review by Lelith — APPROVED** [review]
Looks good to me!

**Comment by denkristoffer** [comment]
@Lelith @burakukula 

I tried combining the Skeleton docs into one page: https://forma-36-git-feat-compound-skeleton.colorfuldemo.com/components/skeleton

What do you think, better or worse?

**Review by Lelith — APPROVED** [review]
i like the one page document better, its easier to read and understand.

**Review by massao — APPROVED** [review]
LGTM, would it be worth to keep a note or something saying that the previous way would still work?? so developers that are already using it, wouldn't keep from updating to this version?? 🤔

**Pull request merged**
