### PR TITLE
feat: add entries and pages icon [SPA-823]

### PR DESCRIPTION
**Pull request by ChidinmaOrajiaku**
# Purpose of PR
- Switch Entry Icon to Page Icon
- Create new Entry Icon image

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/main/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

### CODE REVIEW

**Review by Lelith — APPROVED** [review]

**Comment by Sarah-Roediger** [comment]
Hey @ChidinmaOrajiaku, this was only adding the new icon to the package right? So I cannot see anything on the webapp yet to review? Thanks! 🙏

**Review by massao — CHANGES_REQUESTED** [review]
Hey hey,
Can you double check the SVG for the new EntryIcon?? It looks a bit weird since it's not centralized as the [other icons](https://forma-36-git-feat-add-entries-and-pages-icon.colorfuldemo.com/components/icon#all-icons)

Also this will cause all place using the previous EntryIcon to change to the new one when the package version is updated, should we communicate this somehow, for devs that may be using the old icon??

**Comment by ChidinmaOrajiaku** [comment]
> other icons

Yep that's right.

**Comment by ChidinmaOrajiaku** [comment]
> Hey hey, Can you double check the SVG for the new EntryIcon?? It looks a bit weird since it's not centralized as the [other icons](https://forma-36-git-feat-add-entries-and-pages-icon.colorfuldemo.com/components/icon#all-icons)
> 
> Also this will cause all place using the previous EntryIcon to change to the new one when the package version is updated, should we communicate this somehow, for devs that may be using the old icon??

Thanks for pointing this out. I've fixed it.

**Review by massao — APPROVED** [review]

**Comment by ChidinmaOrajiaku** [comment]
@massao How do I make the rest of the checklist i.e UI Review and UI test pass?

**Comment by massao** [comment]
> @massao How do I make the rest of the checklist i.e UI Review and UI test pass?

Sorry, forgot to review and approve the changes there

**Comment by massao** [comment]
@ChidinmaOrajiaku Just remember to add a changeset, otherwise this will not generate a new version

**Comment by ChidinmaOrajiaku** [comment]
@massao How do I add a changeset?

**Review by SofiaMargariti — APPROVED** [review]

**Pull request merged**
