### PR TITLE
fix(grid): GapTypes typos

### PR DESCRIPTION
**Pull request by colshacol**
# Purpose of PR

I toy around with Forma36 every few months to see what is new. Today I decided I would like to take your Grid / GridItem components for a drive, but I encountered an issue in which they do not seem to be exported from `@contentful/forma-36-react-components@3.67.0`.

([Input](https://user-images.githubusercontent.com/19484365/99481100-02a49e80-291f-11eb-8d1d-0bb27ca0f549.png) and [output](https://user-images.githubusercontent.com/19484365/99481079-f4ef1900-291e-11eb-9ab7-76c913b4b284.png).)

I dug into the repo and found that extracting these 2 components would be relatively simple, so I did. And that is when I encountered this super-massive, show-stopping, brain melting, beast of a bug inside of `Grid.tsx`.

image

I cloned it all down and found that the typo actually exists a few other places, as well.

image

I confirmed that the `2X.` was the standardized format, rather than `2x.`.

image

Fixed up the typos and did a little...

```bash
yarn build
npm rebuild node-sass
yarn-build
nvm install 13
yarn build
npm rebuild node-sass
yarn build
yarn test
```

Build succeeded, tests passed, and here is my PR.

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by burakukula** [comment]
Hello @colshacol 👋 Thank you very much for your contribution and fixing the bug 🎉

**Review by burakukula — APPROVED** [review]

**Review by gui-santos — APPROVED** [review]
Wow!

**Review by denkristoffer — APPROVED** [review]
Thank you for the fix! I think the long term solution here would be to import and re-export the types directly from the tokens package, however it doesn't seem to build its types in a way that works well for this.

**Comment by colshacol** [comment]
Pulled in master to fix conflict of `Grid.md` being renamed to `README.md`.👍

> Thank you for the fix! I think the long term solution here would be to import and re-export the types directly from the tokens package, however it doesn't seem to build its types in a way that works well for this.

I'd gladly submit a PR for this if your team determines if/how it should be carried out!

**Review by mshaaban0 — APPROVED** [review]
Looks Good, thanks @colshacol

**Comment by mshaaban0** [comment]
@colshacol circleci wasn't configured to build forked PRs, can you please force push so it triggers the workflow? thanks.

**Pull request merged**
