### PR TITLE
chore: add script to make versioning and publishing prereleases easier

### PR DESCRIPTION
**Pull request by massao**
# Purpose of PR

Add script to make the handling of prereleases packages easier.

The script will handle:
* bumping the version according to the selected prerelease (alpha, beta)
* adding to the ignore field on changeset configuration
* publish to npm

PS: kept with the `--dry-run` flag for now for testing, will remove it before merging into `main`

### CODE REVIEW

**Review by Lelith — APPROVED** [review]
thank you so much for taking care of this!

**Comment by denkristoffer** [comment]
How, if at all, does this handle having both a stable and a prerelease version of a component? Is that even possible?

**Comment by massao** [comment]
> How, if at all, does this handle having both a stable and a prerelease version of a component? Is that even possible?

It doesn't, it could be possible with a bit more tweaking, because we would need to know if it is a new prerelease our going back to a previous one have to store the information of the prerelease somehow, so there is no version conflict, e.g:

```
alpha -> stable fix -> back to alpha = `alpha.x`
or
alpha -> merge alpha -> new alpha = `4.x.x-alpha.0`
```

For that we could have a json file that store the prerelease versions that weren't merged into stable yet, but we would need to also add a command to mark that we will merge a prerelease package into stable. 🤔 

WDYT?

**Comment by denkristoffer** [comment]
I think that's okay, but we should add documentation specifying that prerelease is only for new components. Or something like that. What do you think?

**Review by denkristoffer — APPROVED** [review]

**Pull request merged**
