### PR TITLE
feat(navigation-icon): add new purchase icon to lib

### PR DESCRIPTION
**Pull request by gui-santos**
# Purpose of PR

My team needs to include this new NavigationIcon

Screenshot 2020-08-17 at 16 42 42

It's going to be used in Contentful's purchase flow redesign

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by burakukula** [comment]
@gui-santos I think we need to replace Subscription icon with something else in that case, they are very similar. We can follow up with Cassie regarding this topic, she was up for helping out to replace those vague icons with something from this set. WDYT?

**Comment by gui-santos** [comment]
> @gui-santos I think we need to replace Subscription icon with something else in that case, they are very similar. We can follow up with Cassie regarding this topic, she was up for helping out to replace those vague icons with something from this set. WDYT?

I agree 100%
I will hold this PR a little bit more then :)

Thanks

**Comment by Gracegross** [comment]
The reason i chose this icon was because it's related to the subscription ... but happy to change it to something else. The new icons aren't coming in time for this, so going to have to use this set

**Comment by Gracegross** [comment]
Suggesting this alternative
shopping-bag-2
 :)

**Comment by burakukula** [comment]
@Gracegross @gui-santos sure thing! No worries, I think we don't have to block this. The subscription icon was considered one of the icons that was vague for users and we wanted to change that. I think in this context, the icon that you have chosen totally make sense. Let's go with it and meantime we can come back to the question if we want to change subscription icon. But it's not a blocker in my opinion.

**Pull request merged**
