### PR TITLE
feat(f36-codemod): ESM

### PR DESCRIPTION
**Pull request by denkristoffer**
# Purpose of PR

ESM codemod to unblock package upgrades.

### CODE REVIEW

**Review by massao — APPROVED** [review]

**Comment by denkristoffer** [comment]
I tried this out locally and it seemed to work fine even with node 14. @massao are there any gotchas or specific situations you think I should test before merging?

**Comment by massao** [comment]
> I tried this out locally and it seemed to work fine even with node 14. @massao are there any gotchas or specific situations you think I should test before merging?

maybe just running it against some other repos??

**Comment by massao** [comment]
btw, should we mark this as a major change on the codemod?

**Comment by denkristoffer** [comment]
I ran the wizard on a part of our web app. Will try out with arguments.

**Pull request merged**
