### PR TITLE
fix: allow change of entry card title tag with prop

### PR DESCRIPTION
**Pull request by YvesRijckaert**
# Purpose of PR

Allow change of entry card title tag with prop

### CODE REVIEW

**Comment by burakukula** [comment]
👋 @YvesRijckaert! Wondering why this is a draft, is there any additional changes that you are planning to do in this PR?

**Comment by YvesRijckaert** [comment]
> 👋 @YvesRijckaert! Wondering why this is a draft, is there any additional changes that you are planning to do in this PR?

Haven't had the time to test it yet, and the build seems to fail. Will try to have a look this week :)

**Comment by gui-santos** [comment]
> Haven't had the time to test it yet, and the build seems to fail. Will try to have a look this week :)

This is why the build is failing:
Screenshot 2022-03-01 at 14 39 41

**Review by Lelith — APPROVED** [review]
Maybe showing the change in a code example in the docs would be very helpful.

Besides that it looks good to me!

**Pull request merged**
