### PR TITLE
docs: show components in the center of the canvas

### PR DESCRIPTION
**Pull request by gui-santos**
What do you think about showing the components in the center of the canvas?

Screenshot 2020-11-13 at 17 52 39

this PR also wraps all stories in a container that sets our font-family, so components like the spinner are not using Times New Roman anymore

P.S.: I had to add a wrapper in the Grid story because the centered layout broke it and then I updated the story to storybook’s new format

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by domarku** [comment]
Love it. J'approve!

**Comment by denkristoffer** [comment]
Looks great ❤️ About the Grid story changes, did we talk about moving to MDX?

**Review by denkristoffer — APPROVED** [review]

**Comment by gui-santos** [comment]
> Looks great ❤️ About the Grid story changes, did we talk about moving to MDX instead of CSF?

Did we? I don't remember
Do we have one component using MDX already that I can use as a model?

**Comment by denkristoffer** [comment]
> Do we have one component using MDX already that I can use as a model?

I don't think so, not yet. Anyway, we can do it later if at all.

**Pull request merged**
