### PR TITLE
[Proposal] feat: navigation links states

### PR DESCRIPTION
**Pull request by gui-santos**
# Purpose of PR

This is just a proposal to start a discussion on how we can align these states until @domarku designs the final version of them

I basically tried to align all the navigation links to follow our TextLink styles:
- hover: the link gets underlined
- active: the link gets bold and underline

Screenshot 2022-01-17 at 11 59 20

### Hover state in sidebar
hover_sidebar

### Hover in ToC
hover_toc

### Hover in Topbar
hover_topbar

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by burakukula** [comment]
@gui-santos cool, I think it's a good beginning. I was thinking similarly, but more to have blue and bold for all of them (the same like we had in the ToC in the sidenav), but your proposal is cool, it makes sense to use links.

**Review by suevalov — APPROVED** [review]
👍🏼

**Comment by gui-santos** [comment]
> @gui-santos cool, I think it's a good beginning. I was thinking similarly, but more to have blue and bold for all of them (the same like we had in the ToC in the sidenav), but your proposal is cool, it makes sense to use links.

@burakukula funny that you said that
because they are all blue and bold when active hahahahaha
well "demi bold" because that's our boldest font weight token

I added an underline to the active state because only blue and bold was not distinguishable enough especially in the top bar

**Comment by burakukula** [comment]
> > @gui-santos cool, I think it's a good beginning. I was thinking similarly, but more to have blue and bold for all of them (the same like we had in the ToC in the sidenav), but your proposal is cool, it makes sense to use links.
> 
> @burakukula funny that you said that because they are all blue and bold when active hahahahaha well "demi bold" because that's our boldest font weight token
> 
> I added an underline to the active state because only blue and bold was not distinguishable enough especially in the top bar

😄 makes sense!

**Review by burakukula — APPROVED** [review]

**Review by thebesson — APPROVED** [review]

**Pull request merged**
