### PR TITLE
feat: Forma V4

### PR DESCRIPTION
**Pull request by suevalov**
# Purpose of PR

This branch is an umbrella for all V4 related changes

### CODE REVIEW

**Comment by mshaaban0** [comment]
Nope, doesn't work! :)

**Comment by denkristoffer** [comment]
Close and create new PR?

**Comment by denkristoffer** [comment]
@suevalov What kind of global styles do you have in mind for `GlobalStyles`?

**Comment by suevalov** [comment]
@denkristoffer reset + typography, default font-size, etc.

**Review by gui-santos — APPROVED** [review]

**Pull request merged**
