### PR TITLE
fix: typo in README.md

### PR DESCRIPTION
**Pull request by benomatis**

### CODE REVIEW

**Review by Lelith — APPROVED** [review]

**Review by massao — APPROVED** [review]

**Comment by benomatis** [comment]
The error (`Error: Error serializing `.topbarLinks` returned from `getStaticProps` in "/[...slug]".`) seen in `circle-ci: check-links` is what I encountered when I tried starting the website package, I worked it around by modifying the `getStaticProps` functions to return an empty array if `getTopbarLinks` returns falsy…

**Review by denkristoffer — APPROVED** [review]
@benomatis Don't worry about that error, it happens when a Circle CI build is not triggered by users in the Contentful organisation because the build job needs privileged keys to fetch the website content. I've authorized the build and everything is green now 😄 Thanks for the contribution!

**Comment by denkristoffer** [comment]
@all-contributors please add @benomatis for doc

**Comment by benomatis** [comment]
cheers @denkristoffer :)

**Pull request merged**
