### PR TITLE
refactor: make spinner three dots again

### PR DESCRIPTION
**Pull request by gui-santos**
# Purpose of PR

spinner

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Review by fabe — APPROVED** [review]

**Comment by denkristoffer** [comment]
Should the dots take the currentColor in buttons? Look at the warning button loading on https://www.chromatic.com/test?appId=5fd1dda724cc620021ace8c5&id=5ff831674dba3500210a4db4

**Review by burakukula — APPROVED** [review]
Great! 🙌

**Comment by gui-santos** [comment]
> Should the dots take the currentColor in buttons? Look at the warning button loading on https://www.chromatic.com/test?appId=5fd1dda724cc620021ace8c5&id=5ff831674dba3500210a4db4

@denkristoffer Oh yes! I think I fixed that only in the v3 branch 🤦 
I will fix it here too, thanks 🙌

**Comment by suevalov** [comment]
@gui-santos is it intended to be merged in `master`?

**Comment by gui-santos** [comment]
> @gui-santos is it intended to be merged in `master`?

@suevalov previously when I reverted to the old spinner, I did it in master and then v3 got rebased
then I thought the fix should be in master as well, but idk I have no strong opinions on this hahaha

WDYT? I can rebase this branch to v3-visual-changes and we make the three dots part of v3 update
whatever we think it's better for me is all good 👌

**Comment by suevalov** [comment]
@gui-santos ah, let's merge to master and merge master to `v3-visual` changes

**Review by suevalov — APPROVED** [review]

**Pull request merged**
