### PR TITLE
fix(breadcrumb): remove max-width

### PR DESCRIPTION
**Pull request by denkristoffer**
# Purpose of PR

Removes `max-width` from breadcrumb buttons.

### CODE REVIEW

**Review by massao — APPROVED** [review]

**Comment by denkristoffer** [comment]
@massao Do I need to bump version manually here? I can't remember for alpha versions 🤔

**Comment by massao** [comment]
> @massao Do I need to bump version manually here? I can't remember for alpha versions 🤔

You can run `build`, and after that run `npm run prerelease`, it starts an interactive prompt to choose package and version, and if it should be published

**Comment by denkristoffer** [comment]
@massao But I should do that for this PR before merging 😄

**Comment by massao** [comment]
> @massao But I should do that for this PR before merging 😄

Yes, since the script also change the version on the package.json 😄

**Pull request merged**
