### PR TITLE
feat(tabs): visual changes

### PR DESCRIPTION
**Pull request by denkristoffer**
# Purpose of PR

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by suevalov** [comment]
I'm not sure about this change. As for me, `Tabs` by themselves should be having a border around them and the border appears when you're using Tabs inside a `Module` component

**Comment by suevalov** [comment]
I'd rather introduce a new property that allows you to use vertical dividers instead of a horizonal one.

`dividerType="vertical"` and by default it will be "horizontal" in v3, so we don't need to make any changes in our main web app.

**Comment by m10l** [comment]
+1 for what Alex said, I think the default should be closer to the existing appearance. Would also be cool if there was an option to remove the first and last borders for the new appearance, I can imagine there being issues in some layouts, but maybe that's something for if/when we run into any issues.

**Comment by denkristoffer** [comment]
> I'm not sure about this change. As for me, Tabs by themselves should be having a border around them and the border appears when you're using Tabs inside a Module component

I see your point, but I think Tabs can be sized differently than the tabs you want to show inside it. I think of Tabs as block level, Tab more like inline. You would also have to do some overrides for disabled tabs to position them on top of the Tabs border.

> dividerType="vertical" and by default it will be "horizontal" in v3, so we don't need to make any changes in our main web app.

V3 seems to divice tabs from content, you are proposing dividing tabs from each other if I understand you correctly?

**Comment by suevalov** [comment]
Screenshot 2021-01-11 at 14 01 04

After a second though it seems that we have several components that have a new "embedded" concept - like Tables, Tabs.

So, I wouldn't change the default look and feel of the V3 for sure, but rather introduce vertical dividers only. And we'll be using them only in new applications without changing the main web app.

**Review by suevalov — APPROVED** [review]

**Comment by mshaaban0** [comment]
> After a second though it seems that we have several components that have a new "embedded" concept - like Tables, Tabs.
> So, I wouldn't change the default look and feel of the V3 for sure, but rather introduce vertical dividers only. And we'll be using them only in new applications without changing the main web app.

+1 to this, tabs and table are considered "Modular Block Components" with two style `embedded` and `inline`.

we need to create a common prop name for these modular components to switch between both, and default it to the current styles to avoid breaking changes

**Review by m10l — APPROVED** [review]
Agree with the comments about inline/embedded - we can come up with something consistent and meaningful before merging the V3 branch

**Pull request merged**
