### PR TITLE
docs: add notes about figma account to the home page part 2

### PR DESCRIPTION
**Pull request by domarku**
# Purpose of PR

Change the URL to automatically create a duplicate
Move the note about a necessary Figma account to the end

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by domarku** [comment]
@denkristoffer you were too quick to close the PR! :) I think I found a better solution for the URL

**Review by denkristoffer — APPROVED** [review]
🙏

**Review by mshaaban0 — COMMENTED** [review]
Screenshot 2021-02-25 at 13 18 49

Why copy? can others just use the same lib we use?

**Review by gui-santos — APPROVED** [review]

**Comment by denkristoffer** [comment]
@mshaaban0 I assume the file is locked from outside contributors.

**Comment by domarku** [comment]
> can others just use the same lib we use?

@mshaaban0 people outside of our Figma organization can't just import our library and use it as we do. https://help.figma.com/hc/en-us/articles/360025508373-Publish-styles-and-components-to-a-library#Publish_to_library

I reached out to our CSM (Katie Latchford) in Figma to see if there's a better way that what we're doing. Keep you posted!

**Pull request merged**
