### PR TITLE
docs: remove maintainers

### PR DESCRIPTION
**Pull request by denkristoffer**
Should we remove the maintainers section now that we have a list of contributors?

### CODE REVIEW

**Review by gui-santos — APPROVED** [review]

**Comment by m10l** [comment]
Testing to see if it's possible to add multiple contributors at the same time, sorry for any spam

@all-contributors please add @thebesson for code
@all-contributors please add @arpl for code

**Comment by m10l** [comment]
So no that didn't work then :)

**Comment by burakukula** [comment]
Maybe it's worth having this section since we are automatically added to PR's and review them, maintain the code, plan for next releases, yada yada? I'm fine with removing this section, it's just a thought.

**Comment by domarku** [comment]
@denkristoffer there's something weird happening with the contributors badge at the top of the file

Screen Shot 2020-12-02 at 16 51 56

**Review by mshaaban0 — APPROVED** [review]

**Comment by denkristoffer** [comment]
Thanks @domarku, fixed in https://github.com/contentful/forma-36/pull/698

**Comment by denkristoffer** [comment]
@burakukula I think it's quite easy to forget to update that section. What if we instead only add maintenance emojis to us 5 for now? Although it's not quite as explicit.

**Review by burakukula — APPROVED** [review]

**Pull request merged**
