### PR TITLE
fix(Readme.mdx): fixed readme doc with correct import directory for custom icons

### PR DESCRIPTION
**Pull request by Lakesxo**
# Purpose of PR
- I realized that custom icons can not be imported from "@contentful/f36-components" rather they are imported from "@contentful/f36-icons" but the docs says otherwise. So I have decided to kindly point this out and improve the page with the right import directory ❤️

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/main/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by denkristoffer** [comment]
👋 Hi @Lakesxo, thanks for the contribution! I see your point here, I had to go back and read it again myself to understand what is going on. The code import is actually the right one, but the comment above it is not explaining what we mean by "custom icons", which leads to confusion.

What the second import tries to tell us is how to render totally custom icons like something from a third-party library https://f36.contentful.com/components/icon#custom-icons-and-third-party-libraries – do you have a suggestion how we can phrase this better? Do you find `// or, for third-party icons` clearer?

**Comment by Lakesxo** [comment]
> 👋 Hi @Lakesxo, thanks for the contribution! I see your point here, I had to go back and read it again myself to understand what is going on. The code import is actually the right one, but the comment above it is not explaining what we mean by "custom icons", which leads to confusion.
> 
> What the second import tries to tell us is how to render totally custom icons like something from a third-party library https://f36.contentful.com/components/icon#custom-icons-and-third-party-libraries – do you have a suggestion how we can phrase this better? Do you find `// or, for third-party icons` clearer?

Oh okay. Yeah i think the third-party icons phrase sounds better. 
But when i tried to import a forma custom icon e.g PlusIcon from "@contentful/f36-components" it didn't work until i imported from "@contentful/f36-icons";

**Comment by denkristoffer** [comment]
@Lakesxo No you're right, that's the way to do it. Maybe we should change the first line to make it more clear too 🤔

**Comment by Lakesxo** [comment]
@denkristoffer Yeah i think you should. Maybe something like:

// Import as an object :
`import * as icons from '@contentful/f36-icons';`
// Import single component as :
`import { PlusIcon, DoneIcon } from "@contentful/f36-icons";`
// Third party custom icons as :
`import { Icon } from '@contentful/f36-components';`


**Access import as an object:**
```
function IconExample() {
     return (
          <>
              {icons.PlusIcon}
              {icons.DoneIcon}
          </>
     )
}
```
OR

**Access import as a single component:**
```
function IconExample() {
     return (
          <>
              <PlusIcon />
              <DoneIcon />
          </>
     )
}
```

**Comment by denkristoffer** [comment]
@Lakesxo That looks good to me 😄 Would you like to update the PR with that?

**Comment by Lakesxo** [comment]
> @Lakesxo That looks good to me 😄 Would you like to update the PR with that?

Sure, will do

**Review by denkristoffer — APPROVED** [review]

**Comment by denkristoffer** [comment]
Thanks for the contribution @Lakesxo! I'm sorry it took so long to get merged 🙇 Thanks again!

**Pull request merged**
