### PR TITLE
feat: keyboard-only focus styles

### PR DESCRIPTION
**Pull request by denkristoffer**
# Purpose of PR

Keyboard-only focus styling.

Have a look at

Accordion
- https://forma-36-git-feat-focus-styles-contentful-apps.vercel.app/components/accordion

Buttons
- Button https://forma-36-git-feat-focus-styles-contentful-apps.vercel.app/components/button
- CopyButton https://forma-36-git-feat-focus-styles-contentful-apps.vercel.app/components/copy-button
- ToggleButton https://forma-36-git-feat-focus-styles-contentful-apps.vercel.app/components/toggle-button

Form elements
- CheckBox https://forma-36-git-feat-focus-styles-contentful-apps.vercel.app/components/checkbox
- Radio https://forma-36-git-feat-focus-styles-contentful-apps.vercel.app/components/radio
- Switch https://forma-36-git-feat-focus-styles-contentful-apps.vercel.app/components/switch

Cards
- https://forma-36-git-feat-focus-styles-contentful-apps.vercel.app/components/card

We've decided to keep the focus styles for inputs.

### CODE REVIEW

**Comment by gui-santos** [comment]
@domarku did you have a chance to check this proposal from @denkristoffer ?

**Review by fabe — APPROVED** [review]
IMO:

1. We should keep the focus glow for both keyboard and mouse interactions on text inputs.
2. We can add `glowPrimary` to `Accordion.Item` for keyboard-only.
  image

Q: The Radio is changing value when tabbing, is that expected?

**Comment by denkristoffer** [comment]
Thanks for chiming in @fabe I will get the Accordion changed as you suggest 👍 

> Q: The Radio is changing value when tabbing, is that expected?

No that sounds wrong. I'm not seeing this in FF or Chrome. Which browser are you using?

**Comment by denkristoffer** [comment]
Next question, what about the Card? This component was one of the reasons I started working on this, but looking at it in the Storybook like this it seems weird not to have the box-shadow:

Screenshot 2022-02-16 at 14 02 41

Ideas?

**Review by mshaaban0 — COMMENTED** [review]
I think the outline is still there 🤔 

Screenshot 2022-02-17 at 10 39 00

**Review by mshaaban0 — APPROVED** [review]
💅🏼

**Pull request merged**
