### PR TITLE
feat: create CheckboxGroup and RadioGroup

### PR DESCRIPTION
**Pull request by massao**
# Purpose of PR

Create CheckboxGroup and RadioGroup to make it easier to handle multiple inputs.
* Let me know if you think they should cover something more.
* I started them as separate files, but decided to merge into `BaseCheckboxGroupContext`, and `BaseCheckboxGroup`  as most of the code was the same, but let me know if you prefer the separate files approach.
* Didn't use the Compound Solution as there may be cases where users may want to use the `Checkbox` or `Radio` without a Group

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by massao** [comment]
Should we do the same for the `Switch` component??

**Comment by suevalov** [comment]
@massao do you think a case for a group of switches?

**Comment by massao** [comment]
> @massao do you think a case for a group of switches?

@suevalov No I couldn't think of any, but if someone can think of one, we could create one, or we can merge this one and if a use case comes to mind later we create a new PR

**Comment by suevalov** [comment]
@massao I don't see use cases either, so I guess we can skip it for now.

**Review by suevalov — APPROVED** [review]
Looks amazing! I love these new components.

**Pull request merged**
