### PR TITLE
feat(pill): add isDraggable prop

### PR DESCRIPTION
**Pull request by denkristoffer**
# Purpose of PR

Add `isDraggable` prop to `Pill` component, which renders the drag handle without passing an `onDrag` prop.

### CODE REVIEW

**Review by massao — APPROVED** [review]
Should we point out that the `dragHandleComponent` is always required when wanting to render the drag handle? And either the `isDraggable` or the `onDrag`, because at the moment we don't have a fallback for the dragHandle component right?? 🤔 

But looks good to me anyway, just an open question

**Comment by denkristoffer** [comment]
@massao There's a built-in fallback although it doesn't use our `DragHandle` component. I was thinking about changing it but I wonder if we initially made it with a `span` for a reason? https://github.com/contentful/forma-36/blob/51a37aa763deeba32b5ca58189e32ca039c51eb4/packages/components/pill/src/Pill.tsx#L84-L86

**Comment by massao** [comment]
> 

Could be because before we didn't have the transparent variant an the DragHandle only had the styling to be used on the cards, if the transparent variant would fit we should use it, right?? It wouldn't add too many dependencies, the DragHandle only depends on the Icon that is already being used here.

**Comment by denkristoffer** [comment]
@massao done.

**Pull request merged**
