### PR TITLE
feat(pill): add pill states

### PR DESCRIPTION
**Pull request by damienxy**
# Purpose of PR

Adding `variant` property to `Pill` component. 
Implementation of https://github.com/contentful/forma-36/issues/585 (see comments from this year).

Screenshot 2021-03-12 at 11 22 11

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

### CODE REVIEW

**Review by suevalov — COMMENTED** [review]
I'd go with `variant` instead of `state`, we want to align all properties in V4.

**Comment by nikazawila** [comment]
this looks real cool @damienxy - thanks for contributing!

**Review by nikazawila — APPROVED** [review]
lgtm 🌻 

thanks for your work!

**Comment by damienxy** [comment]
FIY, also added a fix for the tiny hover misalignment here:
Screenshot 2021-03-12 at 15 00 46

**Pull request merged**
