### PR TITLE
Chore: migrate storybook version 6.0.x

### PR DESCRIPTION
**Pull request by gui-santos**
# Purpose of PR

It updates to the latest version of storybook that has some cool features 🎊 

In order to migrate some refactor was necessary:
- Replace all the `|` with `/` because that's [the only hierarchy separator that Storybook accepts](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#removed-hierarchy-separators) now
- removed some configs from some addons because [they got presets now](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-addon-presets)
- removed addon-notes and addon-info because [they got deprecated](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#60-deprecations)
- storybook is supporting addon-docs to replace notes/info so I added it here and made it generate doc pages from the .md documents we used with the deprecated addons

### Adopting addon-docs
The Docs automatically generates a heading title with the component name and we already had that in our .md files so now the page shows the component name twice 😄 
Screenshot 2020-08-27 at 10 31 02

But instead of just removing the titles I think we should explore [addon-docs](https://github.com/storybookjs/storybook/tree/next/addons/docs), it [generates docs](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#component-story-format-csf-with-docspage) from MDX and from stories written using the new CSF format. And by adopting it for real would fix this issue with the title

### Migrate stories to the CSF format

To get full advantage of addon-docs we might have to migrate stories to the [CSF format](https://medium.com/storybookjs/component-story-format-66f4c32366df) which looks like this:

```js
export default { title: 'atoms/Button' };
export const text = () => <Button>Hello</Button>;
export const emoji = () => <Button>😀😎👍💯</Button>;
```

### Replace addon-knobs with Controls

Controls are addon-knobs but automatically generated from the stories 🤯 
Yes this means every story will get knobs without us writing any more code
(we need to change the way write stories though... so I lied hahahahah)
https://medium.com/storybookjs/storybook-controls-ce82af93e430

I tried to implement it already in the Accordion story, take a look there
I feel that there are still a better way to do it, but it was worth testing it 😄 

That's it I guess, any thoughts?

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by gui-santos** [comment]
... Annnnnnnnd It didn't break the pipeline 👍

**Comment by mshaaban0** [comment]
Do we know what it's complaining about in all docs tabs?

Screenshot 2020-08-31 at 12 32 28

**Comment by gui-santos** [comment]
> Do we know what it's complaining about in all docs tabs?
> 
> Screenshot 2020-08-31 at 12 32 28

Uhmmm not yet, @mshaaban0 ! I will investigate it today
I played with storybook in my pet project this weekend and managed to make it work smoothly 👌 
Maybe the answer is there

**Comment by gui-santos** [comment]
> Do we know what it's complaining about in all docs tabs?
> 
> Screenshot 2020-08-31 at 12 32 28

@mshaaban0 I found some interesting things

first this message is showing up because I put this config in the docs:

```js
docs: {
    disable: true,
},
```

I've done this because in the stories that are not in the CSF format (where we use storiesOf) docgen can't find our props definition and shows a "Nothing found" message

I found two ways of fixing it:

1. adding `.addParameters({ component: Asset })` to storiesOf
2. ... or by converting the stories to the new CSF format

I guess let's go with the first one for now 🙌 

Screenshot 2020-08-31 at 14 47 19
☝️ this is with .addParameters

Screenshot 2020-08-31 at 14 30 46
☝️  this is with CSF

**Review by burakukula — APPROVED** [review]
🎉 Amazing work!! Love it! 
This CSF format looks super nice, I think migration to it would not be a huge thing, count me in when it comes to this migration. I can take couple of component and try to refactor them to the new format.

**Comment by gui-santos** [comment]
> 🎉 Amazing work!! Love it!
> This CSF format looks super nice, I think migration to it would not be a huge thing, count me in when it comes to this migration. I can take couple of component and try to refactor them to the new format.

@burakukula Yes! For now, storybook accepts both so we can slowly migrate... any time we are free we can refactor a story hahhaa

Thanks

**Pull request merged**
