### PR TITLE
feat: enable Badge option on EntryCard

### PR DESCRIPTION
**Pull request by Cyberxon**
# Purpose of PR

In order to properly show the new ExternalResourceCards status badges, this PR aims to enable passing the new Badges as an option `badge` to the `EntryCard` component

image (4)

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/main/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [ ] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Review by cf-remylenoir — COMMENTED** [review]
Thank you for taking care of adding this functionality. 

Could you please reflect this option in the documentation too? https://f36.contentful.com/components/entry-card

We are aligning our Storybook & Docs for a future consolidation.

**Comment by Cyberxon** [comment]
> Thank you for taking care of adding this functionality.
> 
> Could you please reflect this option in the documentation too? https://f36.contentful.com/components/entry-card
> 
> We are aligning our Storybook & Docs for a future consolidation.

Documentation updated with a new Example as you requested

**Comment by cf-remylenoir** [comment]
@all-contributors please add @Cyberxon for issue, code and doc.

**Comment by cf-remylenoir** [comment]
https://github.com/all-contributors please add @Cyberxon for bug, code and doc.

**Comment by cf-remylenoir** [comment]
@all-contributors please add @Cyberxon for bug, code and doc.

**Pull request merged**
