### PR TITLE
feat(icons): Add Toggle icon

### PR DESCRIPTION
**Pull request by crissto**
# Purpose of PR

Add ToggleIcon that's going to be used in the merge app.

Screenshot:
Screenshot 2022-09-14 at 10 31 28

## PR Checklist

- [X] I have read the relevant `readme.md` file(s)
- [X] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/main/packages/forma-36-react-components#commits)
- [X] Tests are added/updated/not required
- [X] Tests are passing
- [X] Storybook stories are added/updated/not required
- [X] Usage notes are added/updated/not required
- [X] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [X] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by denkristoffer** [comment]
I'm trying to figure out why I don't see it on the preview docs: https://forma-36-git-feat-add-toggle-icon.colorfuldemo.com/components/icon 🤔 Might not be a problem...

**Review by denkristoffer — APPROVED** [review]

**Review by mshaaban0 — APPROVED** [review]
Hey thanks for the contribution. 
any plans from design to add this to the Figma UI kit? https://f36.contentful.com/guidelines/adding-icons

**Review by massao — APPROVED** [review]

**Comment by massao** [comment]
Just remember that you need to add a changeset otherwise it won't create a new release

**Comment by sjouli** [comment]
> Hey thanks for the contribution. any plans from design to add this to the Figma UI kit? https://f36.contentful.com/guidelines/adding-icons

it's already in 🙃

**Comment by crissto** [comment]
> I'm trying to figure out why I don't see it on the preview docs: [forma-36-git-feat-add-toggle-icon.colorfuldemo.com/components/icon](https://forma-36-git-feat-add-toggle-icon.colorfuldemo.com/components/icon) 🤔 Might not be a problem...

I tried to test the Next app locally but I can't get it to work. I suppose that if the icon is in storybook it's all good?

**Comment by mshaaban0** [comment]
> > Hey thanks for the contribution. any plans from design to add this to the Figma UI kit? https://f36.contentful.com/guidelines/adding-icons
> 
> it's already in 🙃

@sjouli I can't seem to find it here https://www.figma.com/community/file/1099314541500153018

**Pull request merged**
