### PR TITLE
feat: extract Portal and TabFocusTrap to f36-utils package

### PR DESCRIPTION
**Pull request by suevalov**
# Purpose of PR

* Extracts `Portal` and `TabFocusTrap` to a separate `f36-utils` package
* Updates imports
* Updates snapshots

### CODE REVIEW

**Review by denkristoffer — APPROVED** [review]
👍

**Review by denkristoffer — CHANGES_REQUESTED** [review]
The Chromatic changes look very different, the modal backdrop is gone etc. Is this intended?

**Comment by denkristoffer** [comment]
@mshaaban0 I agree **100%** but I don't mind pushing it to a later PR that thoroughly removes it, which seems outside the scope of this one.

**Comment by mshaaban0** [comment]
Removal can go later yes, but I wouldn't expose it in the new package

**Comment by suevalov** [comment]
@denkristoffer we have the same diff in the v4 branch.... looks like we need to take a look there. I wish we could compare to non-main branch.

**Comment by suevalov** [comment]
@mshaaban0 I agree that this component has to be removed but we need to expose it now in order to be able to proceed with refactoring. it will be only available in `4.0.0-alpha` so it shouldn't be a problem

**Review by denkristoffer — APPROVED** [review]

**Comment by denkristoffer** [comment]
If Chromatic always compares to `master` it's not very helpful here...

**Comment by suevalov** [comment]
@denkristoffer we might need to take a look at their documentation: https://www.chromatic.com/docs/branching-and-baselines

**Pull request merged**
