### PR TITLE
fix(card): don't omit withDragHandle type

### PR DESCRIPTION
**Pull request by denkristoffer**
# Purpose of PR

Reinstates the `withDragHandle` boolean on `Card` component. This prop is required to be able to use `dragHandleRender`.

### CODE REVIEW

**Review by bgutsol — CHANGES_REQUESTED** [review]
Pls, check this discussion first 
https://github.com/contentful/forma-36/pull/1583#discussion_r761977175

I guess, if we need a Card with a drag handle we should provide styling for that first.

**Review by bgutsol — COMMENTED** [review]
Three comments here:
1. If you just pass `withDragHandle` prop, without passing `padding` prop, you won't get any typescript errors that padding should be `none`. As a result, it will be rendered like this:
image

2. If you pass both props with `padding="none"` you still will get a kind of raw card (no padding for content). Is it what we want?
image

3. I would also add some examples with descriptions to component docs and storybook.

**Comment by gui-santos** [comment]
Any news on this PR?

**Comment by denkristoffer** [comment]
I will work on this tomorrow 🙏

**Comment by denkristoffer** [comment]
I'm not sure how to fix the remaining type error. React is complaining about `Ref<any>` not matching the `HtmlDivElement` type from `const DRAG_HANDLE_DEFAULT_TAG = 'div'`. Best I can think of is not using the `Element` constant [here](https://github.com/contentful/forma-36/pull/1851/files#diff-a88dc7ed1ba105783c1298bdecbd105429a43c93d5f24081ee6fa6eea7b9828aR127) and instead rendering either a button or a div in an if statement.

@massao @bgutsol any ideas?

**Comment by massao** [comment]
> I'm not sure how to fix the remaining type error. React is complaining about `Ref<any>` not matching the `HtmlDivElement` type from `const DRAG_HANDLE_DEFAULT_TAG = 'div'`. Best I can think of is not using the `Element` constant [here](https://github.com/contentful/forma-36/pull/1851/files#diff-a88dc7ed1ba105783c1298bdecbd105429a43c93d5f24081ee6fa6eea7b9828aR127) and instead rendering either a button or a div in an if statement.
> 
> @massao @bgutsol any ideas?

I think that dropping the `Element` constant and rendering only one or the other is a good solution, because even if we may be able to fix the typing, it could become too complex to maintain later.

**Review by bgutsol — APPROVED** [review]

**Pull request merged**
