### PR TITLE
feat: rename Paragraph to Text

### LINKED ISSUE #1030: 🐛 Bug - HTML header elements(h1, h2, ...)  in the Paragraph component
# Forma 36 bug report

## Summary
Semantically it's not recommended to use the header elements (h1, h2, h3, h4, h5, h6) in the [Paragraph](https://f36-storybook.contentful.com/?path=/story/typography-paragraph--basic) component. 
https://www.loom.com/share/f67e73b5e134471bbeed30f6ea261f86

### PR DESCRIPTION
**Pull request by denkristoffer**
# Purpose of PR

Renames `<Paragraph />` to `<Text />`. Closes #1030

### CODE REVIEW

**Comment by denkristoffer** [comment]
Chromatic shows differences in the Button story with new icons showing up. Is that a leftover from a previous PR not being accepted as baseline or did this component rename really change that?

**Comment by burakukula** [comment]
@denkristoffer yeah, I think it's a leftover from my PR. Sorry

**Review by thebesson — APPROVED** [review]

**Review by suevalov — APPROVED** [review]
Thanks a lot, it makes much more sense to me now.

**Comment by suevalov** [comment]
@denkristoffer I renamed PR title to `feat:` because it goes to v4 branch anyway.

**Pull request merged**
