### PR TITLE
feat: use the f36 tooltip in the pill component

### PR DESCRIPTION
**Pull request by MohammedAl-Rowad**
# Purpose of PR

Convert the [title tooltip](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) into the [tooltip component](https://f36.contentful.com/components/tooltip) in the [pill component](https://f36.contentful.com/components/pill#__next) and show it only when the text is truncated.

> replaces https://github.com/contentful/forma-36/pull/2052

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/main/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Review by denkristoffer — CHANGES_REQUESTED** [review]
Looks like the new Tooltip span breaks the styling: https://www.chromatic.com/test?appId=5fd1dda724cc620021ace8c5&id=6286567e84c9d3003a4063a3

**Comment by denkristoffer** [comment]
Looks like there are padding changes happening in the snapshots now: https://www.chromatic.com/test?appId=5fd1dda724cc620021ace8c5&id=628ca2cfb10eac004a17571b

I'll try to investigate later

**Comment by MohammedAl-Rowad** [comment]
Hey @denkristoffer 👋 

Sorry for taking a long time to come back to this, got busy with other stuff.


The issue should be fixed now.

**Review by denkristoffer — APPROVED** [review]
No worries, me too. Change looks good to me. Thanks for contributing!

**Comment by denkristoffer** [comment]
@all-contributors please add @MohammedAl-Rowad for code

**Pull request merged**
