### PR TITLE
chore: add logo and favicon to storybook

### PR DESCRIPTION
**Pull request by gui-santos**
# Purpose of PR

Screenshot 2020-09-09 at 10 09 07

This PR replaces storybook logo and favicon with Forma36's logo 
It also updates storybook to 6.0.21

Wdyt?

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

### CODE REVIEW

**Review by burakukula — APPROVED** [review]
YES! ♥️

**Review by m10l — APPROVED** [review]

**Review by joaoramos — APPROVED** [review]
👏

**Comment by domarku** [comment]
👍

**Review by domarku — APPROVED** [review]

**Review by mshaaban0 — APPROVED** [review]
🍬

**Comment by gui-santos** [comment]
Thanks, everyone for the approvals!
you were faster than my fix in the logo distortion, but I will comment here to document the process and the decision

So I will make the logo a fixed size because then it does not distort when the user resizes the sidebar
logo_fixed_size

I tried to make it 2x bigger than the minimum, but that's too much (????)
logo_2x

And then I tried 1.5x bigger and the distortion is really bad
logo_1_5x


If we want to change it... we change it 👌 

P.s.: I'm also fixing the favicon in the deployed version. I forgot to add it in the build cmd 🤦

**Comment by domarku** [comment]
@gui-santos Just opened it now and saw that the logo is blurry. I assume it would be sharp if we uploaded an @2x version of the png, double the size.

**Comment by gui-santos** [comment]
> @gui-santos Just opened it now and saw that the logo is blurry. I assume it would be sharp if we uploaded an @2x version of the png, double the size.

@domarku hmmm I will try this later! Thx

**Pull request merged**
