### PR TITLE
chore(deps): migrate from enzyme to @testing-library/react

### PR DESCRIPTION
**Pull request by denkristoffer**
# Purpose of PR

Migrate from `enzyme` to `@testing-library/react`. This is to align testing libraries used across components, to more quickly allow for major React upgrades, and to unblock #611. 

There's still a single component on enzyme, `InViewport.test.tsx`:

These tests use enzyme's `instance()` which testing-library [doesn't support](https://testing-library.com/docs/react-testing-library/migrate-from-enzyme#triggering-class-methods-in-tests-wrapperinstance):

> As we already discussed, we are against testing implementation details and things that uses are not aware of it, and we aim to test and interact with the component like how our users would.

I'm not sure how to test it without rewriting the component completely, which defeats the purpose.

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Review by mshaaban0 — APPROVED** [review]
Very nice, well done 👏

**Review by m10l — APPROVED** [review]
Awesome. We'll be able to deprecate InViewport soon, I wonder what peoples thoughts are on just removing the test so that we can completely get rid of Enzyme?

**Comment by denkristoffer** [comment]
@m10l I'm for it, but I don't really have an idea of how much `InViewport` is used outside of Forma.

**Review by gui-santos — APPROVED** [review]
GREAT!

I vote for removing the enzyme test as @m10l suggested

**Comment by denkristoffer** [comment]
I've deleted the test and removed enzyme completely 👍

**Pull request merged**
