### PR TITLE
feat(website): update copy guidelines

### PR DESCRIPTION
**Pull request by denkristoffer**
# Purpose

Updates the website copy guidelines as per #978 

I don't think our markdown styling is doing too well here, it could use some more spacing.

@Gracegross please have a look at the preview at https://deploy-preview-993--forma-36.netlify.app/guidelines/copy/ux-writing-principles/ 🙂

### CODE REVIEW

**Comment by Gracegross** [comment]
Looks great! Is it possible to replace the ⚠️ icon with ❌ or something like? The hazard icon doesn't come out properly

**Review by burakukula — APPROVED** [review]
LGTM. Thx for pushing this forward! Awesome! 🎉

**Review by mshaaban0 — APPROVED** [review]
💯 👌🏼

**Review by burakukula — APPROVED** [review]

**Comment by denkristoffer** [comment]
Netlify seems to keep the Gatsby cache across builds so I can't get the preview to reflect the latest changes. I'll merge this PR and we can do any follow-up changes in a new PR.

**Pull request merged**
