### PR TITLE
refactor: compound components

### PR DESCRIPTION
**Pull request by suevalov**
# Purpose of PR

Makes `Grid`, `Tabs`, `List`, and `Accordion` to follow a compound component pattern.

### CODE REVIEW

**Review by denkristoffer — APPROVED** [review]
🙏

**Review by bgutsol — APPROVED** [review]
Awesome 👍

Only one comment: I remember @gui-santos was saying that we don't need to pass ['__docgenInfo'] in stories anymore. It's working automagically 🎩 Please correct me if I'm wrong @gui-santos .

**Comment by gui-santos** [comment]
> Awesome 👍
> 
> Only one comment: I remember @gui-santos was saying that we don't need to pass ['__docgenInfo'] in stories anymore. It's working automagically 🎩 Please correct me if I'm wrong @gui-santos .

@bgutsol you are correct!

We had to do this when we started using storybook docs because at that time we didn't have a MDX file for each component, and that's how storybook recommended people to do the migration

**Comment by suevalov** [comment]
Ah, good to know. We can delete all `['__docgenInfo']` as a follow up PR.

**Pull request merged**
