### PR TITLE
chore(AssetCard): align possible entity status

### PR DESCRIPTION
**Pull request by Spring3**
# Purpose of PR

Align possible entity statuses with [field-editor-helpers](https://github.com/contentful/field-editors/blob/master/packages/_shared/src/utils/entityHelpers.ts#L169-L186)

forma was missing the `deleted` status

## PR Checklist

- [ ] I have read the relevant `readme.md` file(s)
- [ ] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Storybook stories are added/updated/not required
- [ ] Usage notes are added/updated/not required
- [ ] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [ ] Doesn't contain any sensitive information

### CODE REVIEW

**Review by denkristoffer — COMMENTED** [review]
And just to be sure, there's not meant to be any visual changes for deleted assets?

**Comment by Spring3** [comment]
I am not aware of any required changes to the Asset card in a deleted state. If that would be required, then we should be able to address it in the next PR, but here I just added the missing status because using AssetCard in typescript environment doesn't accept the "deleted" status no and then it ends with a build error due to type mismatch and we have to cherry pick that value just to match the expected set of strings

**Comment by mshaaban0** [comment]
I think `deleted` and `archived` should have the same styles, similar to `Tag` component?
Also I'm not sure if there's a better way to centralise `entity-types`, maybe a separate package like browser config?
//cc @suevalov

**Comment by Spring3** [comment]
Or maybe using something like contentful-types where we expose these. Cause I think its too small of a change for another package. But these are just some of my thoughts off the top of my head

**Review by denkristoffer — APPROVED** [review]

**Pull request merged**
