### PR TITLE
Fully-automate development setup with Gitpod

### PR DESCRIPTION
**Pull request by shaal**
# Purpose of PR

The purpose of this PR is to fully automate the dev setup of Forma 36 with Gitpod, providing anyone with a pre-built, browser-based development environment in one click:

[Open in Gitpod](https://gitpod.io/from-referrer/)

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by anilkk** [comment]
@shaal Thanks for the PR. We are welcome to contributions directly related to the improvements to the Forma 36 design system. However, this PR is not associated with Forma 36 design system improvement. 

This repository is independent of **code editor configuration**. Therefore, it's up to developers to choose the code editor of thier choice. 

We understand the benefits of coding on the browser using tools like Codespaces and Stackblitz. Do you have any specific reason why you would like to add Gitpod config to this repository?

**Comment by shaal** [comment]
Hi @anilkk 
Adding `.gitpod.yml` to a project, doesn't force developers to use Gitpod, it just gives them a choice. They can still use any other tool they want.

The benefits of Gitpod (just to mention a few) -
* Gitpod is free and available now (Github codespaces is currently in a private beta, still unknown whether it will be free or when will it be publicly available), here's a comparison in the meantime - https://www.gitpod.io/gitpod-vs-github-codespaces
* Gitpod uses a `prebuild` process, processes like `yarn install` will run ahead of time, so developers get a workspace that is ready to code.
* Every new PR - will automatically have a button added (like this PR's, `open on Gitpod`), allowing for the simplest developer onboarding process.
* Gitpod is running on fast machines in the cloud and will run as fast even when running on a tablet (vs. Stackblitz that depends on the power of your machine).
* Gitpod workspaces are available for at least 14 days, so unsaved work never gets lost.

**Comment by anilkk** [comment]
Thanks for the response, @shaal. It's out of scope for us now. However, we may consider your suggestion in the future.

**Comment by shaal** [comment]
Awesome, thank you @anilkk

**Pull request closed without merging**
