### PR TITLE
Added super/sub script icons

### PR DESCRIPTION
**Pull request by azubanych**
# Purpose of PR

Added icons for superscript and subscript functions for the rich-text in contentful

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Comment by burakukula** [comment]
Hello @azubanych! Thank you for your contribution! 🙌
Would you mind sharing from which set of icons, the once added by you are coming from?
We are trying to keep the icons set consistent, so i would also ask @domarku to have a look over here. 🙇‍♀️

**Comment by azubanych** [comment]
> Hello @azubanych! Thank you for your contribution! 🙌
> Would you mind sharing from which set of icons, the once added by you are coming from?
> We are trying to keep the icons set consistent, so i would also ask @domarku to have a look over here. 🙇‍♀️

Hello, @burakukula I've added icons from https://rsuitejs.com/tools/icons/. But I little bit changed them because on build preview they looked bad

**Comment by burakukula** [comment]
@azubanych I would suggest to go with icons from material design https://material.io/resources/icons/?style=baseline . All the icons are coming from there (@domarku correct me if I'm wrong). It would be great to keep it consistent. Would that work for you?

**Comment by azubanych** [comment]
> @azubanych I would suggest to go with icons from material design https://material.io/resources/icons/?style=baseline . All the icons are coming from there (@domarku correct me if I'm wrong). It would be great to keep it consistent. Would that work for you?

Yes, it is not a problem for me to change them. I also was looking at material design but I thought that the icons that I chose will look better, but this is my point of view :smiley:

I will change them, thanks for replying me

**Comment by burakukula** [comment]
> > @azubanych I would suggest to go with icons from material design https://material.io/resources/icons/?style=baseline . All the icons are coming from there (@domarku correct me if I'm wrong). It would be great to keep it consistent. Would that work for you?
> 
> Yes, it is not a problem for me to change them. I also was looking at material design but I thought that the icons that I chose will look better, but this is my point of view 😃
> 
> I will change them, thanks for replying me

No problem! Thank you very much for an update! 🙇‍♀️

**Comment by azubanych** [comment]
> > > @azubanych I would suggest to go with icons from material design https://material.io/resources/icons/?style=baseline . All the icons are coming from there (@domarku correct me if I'm wrong). It would be great to keep it consistent. Would that work for you?
> > 
> > 
> > Yes, it is not a problem for me to change them. I also was looking at material design but I thought that the icons that I chose will look better, but this is my point of view 😃
> > I will change them, thanks for replying me
> 
> No problem! Thank you very much for an update! 🙇‍♀️

@burakukula Changed :innocent:

**Comment by domarku** [comment]
Hi @azubanych, thanks for your contribution! So far we've been using icons from the Material design system where possible. As @burakukula said, we'd like to keep the icon set consistent. If there weren't appropriate icons in Material, we would welcome a proposal from another set or a custom designed one.

**Review by domarku — APPROVED** [review]

**Comment by azubanych** [comment]
> Hi @azubanych, thanks for your contribution! So far we've been using icons from the Material design system where possible. As @burakukula said, we'd like to keep the icon set consistent. If there weren't appropriate icons in Material, we would welcome a proposal from another set or a custom designed one.

Thanks a lot!

**Review by burakukula — APPROVED** [review]
@domarku thx for feedback 🙇‍♀️

**Comment by gui-santos** [comment]
@azubanych @burakukula @domarku can we merge this?

**Comment by azubanych** [comment]
> @azubanych @burakukula @domarku can we merge this?

As from my side - yes. 

Also, I've opened another PR for rich-text types. But there are no reviewers assigned: https://github.com/contentful/rich-text/pull/191
Could somebody check this?

**Comment by domarku** [comment]
Yup, ready to merge 👍

**Pull request merged**
