### PR TITLE
chore: generate token types

### PR DESCRIPTION
**Pull request by suevalov**
# Purpose of PR

Automatically generate token-based typescript types.

### CODE REVIEW

**Review by denkristoffer — COMMENTED** [review]
I think we kind of get the "F36" namespace automatically by importing from `@contentful/f36-tokens`, do you think it's worth keeping for all types?

**Comment by suevalov** [comment]
@denkristoffer I guess we can rename to `SpacingTokens`, `BorderRadiusTokens`, `GlowTokens`, etc...

**Review by denkristoffer — APPROVED** [review]
🙏

**Review by gui-santos — APPROVED** [review]
Wow! That's magical

🧙

**Pull request merged**
