### PR TITLE
docs: add note about non-interactive elements to popover

### PR DESCRIPTION
**Pull request by massao**
# Purpose of PR

Add note about non-interactive elements on popover documentation

### CODE REVIEW

**Comment by denkristoffer** [comment]
I'm not sure I agree with this, we're explicitly saying in the line above that you should use an interactive element, and then we give a way to hack around that?

**Review by bgutsol — COMMENTED** [review]
Agree with @denkristoffer it shouldn't be in the `Content guidelines` section

**Comment by bgutsol** [comment]
> yeah, I was unsure where to put it too, I thought to add at the bottom of the page But could be weird to be after accessibility, so maybe at the bottom of the examples, WDYT?

Yes, let's put it there

**Comment by denkristoffer** [comment]
Unrelated to this PR, but I can't see the change on the Vercel preview, probably because of caching. Would be nice to get that fixed.

**Review by denkristoffer — APPROVED** [review]
Thanks for fixing the build! It seems a bit weird to me to have a note below the examples, but to be honest I don’t have a better suggestion :shrug:

**Review by bgutsol — APPROVED** [review]
I've added a commit with the suggestion, used our Note component to make it more isolated from other content, WDYT?

**Comment by denkristoffer** [comment]
Yeah, nice! Are the code tags supposed to work inside the Note?

Also, when we use the Note like this I think we can move it to content guidelines again, what do you think?

**Pull request closed without merging**
