### PR TITLE
feat: add onClick prop to breadcrumb [CFCX-1433]

### PR DESCRIPTION
**Pull request by massao**
# Purpose of PR

We want to be able to pass custom onClick to breadcrumb to be able to use tracking and similars.

### CODE REVIEW

**Review by denkristoffer — COMMENTED** [review]
Don't forget the changeset.

**Comment by massao** [comment]
> Don't forget the changeset.

This is still in alpha, adding changeset ignores alpha and beta currently, something that we need to take a look into as well

**Review by denkristoffer — APPROVED** [review]
Well in that case!

**Review by miguelcrespo — APPROVED** [review]
Would be cool to update the documentation to show this new possibility:
https://f36.contentful.com/components/header 
File: https://github.com/contentful/forma-36/blob/40700191b96113a2dc1b7b57197daf5632afbef6/packages/components/header/examples/WithBreadcrumbs.tsx#L18

**Review by Lelith — APPROVED** [review]
Looks good to me!

**Pull request merged**
